name: Code Hygiene

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Make All
      run: make

    - name: Testdata upload
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: testdata
        path: ${{ github.workspace }}/testdata
        if-no-files-found: error
